#pragma config(Sensor, dgtl1,  RampR,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  RampL,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  up,             sensorDigitalOut)
#pragma config(Sensor, dgtl4,  down,           sensorDigitalOut)
#pragma config(Motor,  port1,           TLD,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TRD,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Lramp,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Tfeed,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Bfeed,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Llaunch,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Rlaunch,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Rramp,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BRD,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BLD,           tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void Drive(int power)
{
	motor[TLD] = power;
	motor[TRD] = power;
	motor[BLD] = power;
	motor[BRD] = power;

}
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
Drive(127);
wait1Msec(2000);
Drive(0);

  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................

	// Drive function
	motor[TRD] = vexRT[Ch2];
	motor[BRD] = vexRT[Ch2];
	motor[TLD] = vexRT[Ch3];
	motor[BLD] = vexRT[Ch3];

	//launch
	motor[Rlaunch] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
	motor[Llaunch] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;

	//Feed
	motor[Tfeed] = (vexRT[Btn6U]*127 + vexRT[Btn8D]*-127);
	motor[Bfeed] = (vexRT[Btn6D]*127 + vexRT[Btn8D]*-127);

	//ramp
	motor[Rramp] = (vexRT[Btn7U]*127 + vexRT[Btn7D]*-127);
	motor[Lramp] = (vexRT[Btn7U]*127 + vexRT[Btn7D]*-127);

	//Phnematic ramp
	if (vexRT[Btn7L] == 1)
	{
		SensorValue[RampR] = 1;
		SensorValue[RampL] = 1;
	}
	//Collapse
	if (vexRT[Btn7R] == 1)
	{
		SensorValue[RampR] = 0;
		SensorValue[RampL] = 0;
		SensorValue[up] = 0;
		SensorValue[down] = 0;
	}

	//Phenmatic Pop UP
	if (vexRT[Btn8U] == 1)
	{
		SensorValue[up] = 1;
		SensorValue[down] = 1;
	}
	  // .....................................................................................

	}
}
