#pragma config(Sensor, dgtl1,  RampO,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Feed,           sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl4,  RampI,          sensorDigitalOut)
#pragma config(Motor,  port1,           Launch1,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           TRDrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           TLDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           BLDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Feed,          tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Launch2,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
void drive(int Power)
{
	motor[TRDrive] = Power;
	motor[BRDrive] = Power;
	motor[TLDrive] = Power;
	motor[BLDrive] = Power;
}

void Fire(int F)
{
	motor[Launch1] = F;
	motor[Launch2] = F;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
drive(127);
wait1Msec(1800);
drive(0);
Fire(127);
wait1Msec(1000);
Fire(0);
  // .....................................................................................

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................

	//Drive
		motor(TRDrive) = vexRT[Ch2];
		motor(BRDrive) = vexRT[Ch2];
		motor(TLDrive) = vexRT[Ch3];
		motor(BLDrive) = vexRT[Ch3];

// Launcher
	if(vexRT[Btn5U] == 1)
	{
		motor(Launch1)= 127;
		motor(Launch2)= 127;
	}
	else if(vexRT[Btn5D] == 1)
	{
		motor(Launch1) = -127;
		motor(Launch2) = -127;
	}
	else
	{
		motor(Launch1) = 15;
		motor(Launch2) = 15;
	}

	//Feed
	if(vexRT[Btn6U] == 1)
	{
		motor(Feed) = 127;
	}
	else if(vexRT[Btn6D] == 1)
	{
		motor(Feed) = -127;
	}
	else
	{
		motor(Feed) = 0;
	}


	// Launcher/Ramp phenmatic
		if(vexRT[Btn8D] == 1)
		{
			SensorValue[RampO] = 1;
		}
		if(vexRT[Btn8R] == 1)
		{
			SensorValue[RampO] = 0;
		}


	//continous feed phenmatic
	SensorValue[Feed] = 1;


	  // .....................................................................................

	}
}
