#pragma config(Motor,  port1,           top,           tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           bottom,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1==1)
{
	motor[top] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
	motor[bottom] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
}


}
