#pragma config(Sensor, in1,    AutoMatch,      sensorPotentiometer)
#pragma config(Sensor, in2,    RedBlue,        sensorPotentiometer)
#pragma config(Sensor, in3,    RightLeft,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  up,             sensorDigitalOut)
#pragma config(Sensor, dgtl6,  down,           sensorDigitalOut)
#pragma config(Motor,  port1,           LeftTD,        tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftBD,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           TFeed,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BFeed,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LTFeed,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RBFeed,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           TLauncher,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           BLauncher,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RightTD,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RightBD,       tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////1	q////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

//Drive
void RightDrive(int power)
{
	motor[RightTD] = power;
	motor[RightBD] = power;
}

void LeftDrive(int power)
{
	motor[LeftTD] = power;
	motor[LeftBD] = power;
}

void AllDrive(int power)
{
	RightDrive(power);
	LeftDrive(power);
}

int rotat;

void DriveQuad(int Rpower, int Lpower, int rot)
{
	SensorValue[RightQuad] = 0;
	SensorValue[LeftQuad] = 0;
	while(abs(SensorValue[RightQuad]) < rot)
	{
		rotat = rot;
		motor[RightTD] = Rpower;
		motor[RightBD] = Rpower;
		motor[LeftTD] = Lpower;
		motor[LeftBD] = Lpower;
	}

	AllDrive(0);
}

//Feed
void Feed(int x)
{
	motor[TFeed] = x;
	motor[BFeed] = x;
	motor[LTFeed] = x;
	motor[RBFeed] = x;
}

//Feed/Quad combinatino
void QuadFeed(int Rpower, int Lpower, int rot,int FPower)
{
	SensorValue[RightQuad] = 0;
	SensorValue[LeftQuad] = 0;
	while(abs(SensorValue[RightQuad]) < rot)
	{
		motor[RightTD] = Rpower;
		motor[RightBD] = Rpower;
		motor[LeftTD] = Lpower;
		motor[LeftBD] = Lpower;
		motor[TFeed] = FPower;
		motor[BFeed] = FPower;
		motor[LTFeed] = FPower;
		motor[RBFeed] = FPower;
	}
	AllDrive(0);
	Feed(0);
}


//Launch
void Launch(int FirePower)
{
	motor[TLauncher] = FirePower;
	motor[BLauncher] = FirePower;
}

//task liftControl() {
//	while (true) {
//		motor[LLift] = -15;
//		motor[RLift] = -15;
//		liftProgress = 1;
//		while (vexRT[Btn8R] == 0) { EndTimeSlice(); iterations++; }
//		liftProgress = 2;
//		while (vexRT[Btn8R] == 1) { EndTimeSlice(); iterations++; }
//		motor[LLift] = 127;
//		motor[RLift] = 127;
//		liftProgress = 3;
//		while (vexRT[Btn8R] == 0) { EndTimeSlice(); iterations++; }
//		liftProgress = 4;
//		while (vexRT[Btn8R] == 1) { EndTimeSlice(); iterations++; }
//	}
//}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
	int Match = 0;
	int programskill = 0;
	int Red = 0; // which side
	int Blue = 0;
	int inside = 0; //Which square
	int outside = 0;
	SensorValue[RightQuad] = 0;
	SensorValue[LeftQuad] = 0;

	if(SensorValue[AutoMatch] < 2047) // Programing skills or match
	{
		programskill = 1;
	}
	else {
		Match = 1;
	}

	if(SensorValue[RedBlue] < 2047) //red Square or blue Square
	{
		Red=1;
	}
	else {
		Blue=1;
	}

	if(SensorValue[RightLeft] < 2047) // Outside tile or inside tile
	{
		outside=1;
	}
	else {
		inside=1;
	}
	//-------------------------------------------------------------------------------------------------------------------

	// DriveQuad(int Rpower, int Lpower, int rot)
	// QuadFeed(int Rpower, int Lpower, int rot,int FPower)

	if (Match == 1 && Red == 1 && inside == 1)// Red side, inside tile
	{
		DriveQuad(127,127,100);
		DriveQuad(127,-127,5);
		DriveQuad(127,127,5);
		DriveQuad(127,-127,5);
		DriveQuad(127,127,80);
		DriveQuad(-127,127,5);
	}

	if(Match == 1 && Red == 1 && outside == 1)// Red side, outside tile
	{
		DriveQuad(127,127,2000);
		DriveQuad(-127,127,5);
		DriveQuad(127,127,5);
		DriveQuad(-127,127,5);
		DriveQuad(127,127,100);
	}

	if(Match == 1 && Blue == 1 && inside == 1)// Blue side, Inside tile
	{
		DriveQuad(127,127,100);
	}

	if(Match == 1 && Blue == 1 && outside == 1)// Bluse side, Outside tile
	{
		DriveQuad(127,127,100);
	}

	if(programskill == 1 && Blue == 1 && outside == 1)//Blue side, outside tile, scoring
	{
		QuadFeed(127,127,100,127);
	}

	if(programskill == 1 && Red == 1 && inside == 1)// Programing skills program
	{
				DriveQuad(127,127,100);
	}
}
	  // .....................................................................................




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................


		// Drive function
		motor[RightTD] = vexRT[Ch2];
		motor[RightBD] = vexRT[Ch2];
		motor[LeftTD] = vexRT[Ch3];
		motor[LeftBD] = vexRT[Ch3];

		//launch
		motor[TLauncher] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
		motor[BLauncher] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
		motor[LTFeed] = vexRT[Btn5U]*127 + vexRT[Btn5D]*-127 + abs(vexRT[Btn5D] - 1)* abs(vexRT[Btn5U] - 1)*15;
		//Feed
		motor[TFeed] = (vexRT[Btn6U]*127 + vexRT[Btn6D]*-127);
		motor[BFeed] = (vexRT[Btn6U]*127 + vexRT[Btn6D]*-127);

		motor[RBFeed] = (vexRT[Btn6U]*127 + vexRT[Btn6D]*-127);
		//ramp
		//motor[RLift] = vexRT[Btn7U]*127 + vexRT[Btn7D]*-127 + abs(vexRT[Btn7D] - 1)* abs(vexRT[Btn5U] - 1)*-15;
		//motor[LLift] = vexRT[Btn7U]*127 + vexRT[Btn7D]*-127 + abs(vexRT[Btn7D] - 1)* abs(vexRT[Btn5U] - 1)*-15;

		//Collapse
		if (vexRT[Btn7L] == 1)
		{
			SensorValue[up] = 0;
			SensorValue[down] = 0;
		}

		//Phenmatic Pop UP
		if (vexRT[Btn7R] == 1)
		{
			SensorValue[up] = 1;
			SensorValue[down] = 1;
		}

		EndTimeSlice();
		  // .....................................................................................
	}
}
